[secrets.url]
ai_base_url = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NjlkbWdOS0czWTZ6Qk5U
NktVajM1UU5GRUtRSmppR0FtT3VyZU9FNjJZCkVXekRRQzdBQWVCYk4xNTM4d01W
eG1SMXlBa2pUcno0MlVERVQwYTJ0SGMKLS0tIGJJb3M3aVhBbVdFVTBlSFFoQ2pN
N0xDbGlRa2loalF0WjBQdUR4NU1OczQKMHQgHmi81K8f/5UM/obNAtQFjPNHpEw3
nmMi4eBELKjXp+j0DT8HL98UJiBE8UjiQbPOley2ww==
-----END AGE ENCRYPTED FILE-----'''

[secrets.keys]
tavily_token = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucDFCcE1wVjU3REtra25R
Z21oVS9qSEY4NGZobzJMZzJpM0dSMFF0c1RFCk02TCtIZktoTXVWMjduSStoNlJn
MTgrTmRCRXN1TmtwWmV0STZHNDN5KzAKLS0tIGJRR1RzUjB6VjRmRW8yU1U2V1dz
SVdiTEVWOGhPRE9sWUlnMHRJWGdCRWsKzFeUmGahqMfk1Gr8/sv/BHLnMoOszELz
drZsRrzUjYYvneC+J6Q5DjnQzKp92HcbpuHcwJvWQlptgiI5bBHTd9x1ZX9LexGL
iKA=
-----END AGE ENCRYPTED FILE-----'''
waka_time_token = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIblQ0TndaL0o2QUZSbzFj
UGZ4UWNVWnZ4cGdXWXBOYzRpNWxIZlFIZVgwCm91ck1RSkxXRlBQZHlCRVY0QUs4
aDJpR21BbEVXL2F1aFo1WGN0NFZsc1EKLS0tIFdKS2lWVmQ1YnczSEFFTktRb0tF
UnJFY1lKQmE1Ti9PWktpclZSQ2VQUncKJJGSDiKTnMF8rqrVPXGsswM3soSkTeSW
N4UAEBrnG1vgXriSz/sfpmBEjsn+wKqBgMJ8XnzgnoH/m4WXKKkIvfaoMDZro/By
Hg==
-----END AGE ENCRYPTED FILE-----'''
ai_base_token = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeUNrOTgrT2IveG1TK0Rp
ck83dkhIVTdadGRRcXh5V1JFSjJBWkJLWlZnCjVPNmY1dlVMd2YvNjdtTTNYajB6
RExUQU10YVE4aEVyM0VEQWFTczEybjAKLS0tIGhWTFVDSUdqQzg0M0pvdDUrVG9O
dHBtTUZlajRtTUpyNkxwTGVsMDI2MlEKP/+yanzp3muJB4JYdZE0iUw8hPyjODBA
fLxcGMpj67RZzuWAkT1vmLkNdsZ1bunxbkjofRt8hvd0kP43i2qXoix5b5pr6OkM
zUbyIZYH/T6wyyA=
-----END AGE ENCRYPTED FILE-----'''
gpg_for_trust = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MGVodEdhNkxTZzRwNmJO
R1BURjQrQWN2STJqUnVDaERLbHdjREdHdVdZCnRueDJ6V2VBYUllN3N2K3haclBk
NXVwczNOcjY1WXN5a2MyOXJMUjBETEkKLS0tIGZYKzZWR3U5bTBOajhBeGdidE01
NGhTY080TWdqb0t2bGR1d0U1Q0wrOXMKwKjSQfNU/LvpQ3ri3iUSBoDkIEHN72Yr
dHisf3fZeJRCW3uwtDImBaTXPg1pEL8zLFTY7KaHrP6PAZbiMQ4zGNtIAjfqKPo3
-----END AGE ENCRYPTED FILE-----'''
gpg_for_git_sign = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweVRWejJ4Vmc2dTAzVkNj
QS9BK05zRE9Gd0xYSXROaW84cEZGclRPNTFrCmFLQ0dmTGZBYi9IbTlHYVBiR2M3
KytOWVBrYmRzcUdiaE9HVjNSeXFxcFEKLS0tIGlsbnA1WncwL1hudDVEM2w0eGhD
eTBsK2I1SFJxUlVDOXluOEJMempVeUUKAj6IFAKQ2NbNhOlT9Gvy+7J8HfC6G8Og
5PCLJ2YlyAjxwbo49rt1MNCInENhJmDb
-----END AGE ENCRYPTED FILE-----'''
gpg_for_ssh = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGtOS3hTVDBrWlk3ZDRn
bExDdmVMN1lValVFTmZ4M2JFZzBXdnAzVVVZCmU4QW5hQ092dW1KdldJdDVMTzR2
OXIzWHk3Mk1vNHd3YlBKYkZQbXBXek0KLS0tIEpudzZjL3JlcEhiRjFNSW1GcDFG
MEtRY2poTTh5RElXMGhscG10OHR6Nm8KLM+LxX5iAlFB+yGuS4FDnTzPkAOrvg3N
6fIEBN4waMUWtPYKoQWJ6yQB14vbecVIBYT6Dm6HhDHk8TO7jQVhjzBhPeHZiv5g
-----END AGE ENCRYPTED FILE-----'''
ssh_authorized_key = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1enhpZGR0dW1DRU5QVmsr
Yytvc0ZZM1BMZFZ3bFNud3NkMFFXdmYyT24wCk9sOFpYdnlIZEFFM3UyUUdDSWh1
ZGp3RE0yd0FXZXJOTy9QV3NKK201QnMKLS0tIEJlVjh4eWVDODZTT3Jlck1SSTk5
TlN5SDBHNTVNMTIrOVJaNitmbzAyLzAKMmHWxLpsdVrovsKWnzYvjqBdop4pehC/
EKFEXMqEzssUZGh33yLkJkfHhA9+aYBJalkANgdCCuFEvnJP1Pd/IwtyvV+AU27A
7bIZbC0bFBOyKmlRSreZ6vBMGlncnrikpH8DH4fn56uVZ1Up0+fpEqvt0MIA2sk=
-----END AGE ENCRYPTED FILE-----'''

[secrets.license.listary]
email = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpanZsUGFWWDJOeC9IdUxa
SmdPQVFNZEZwODdoTE1LblFPd3VjOUxGRTJnCm9iV0cwREs5c3lKZU96N29iSGlF
ZTBySmNaeExRcXovZHF3VWY1azgrSEUKLS0tIEVFK3lCblYrVXBweEpjZW0wRzgz
QkprdlJPb2NQTDBkZUVqYzNqbEZ2RkkKfP723y5dT7mTRgv+TrhiuBitxm8RRjP0
jM7bZqDSLxQGWFPp6ld4Vy+D3Sk+Pf8BymzC/bc=
-----END AGE ENCRYPTED FILE-----'''
key = '''-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NUlHWjhjeG5LU2FCVHNv
bWNibjFzZGlvL2pjTmlqN1JXTWlGOUJWUkZvCkFlUXNnVkJMb0dQdUM2UjVoL2Fk
c08rYWU2cXcyeEVrRk93NHJQSnkvUFEKLS0tIFhOeTg5MlJOc0VWQktucEdzQVQx
cks0U2dzUjFJY1pTUFVqT29NbTExb3cKZ6n2MWpRvN0f27GUtmsWPi9M3xO5CH9S
LKJJWS7iyvRnS5I3FjWpQOlGOr7VywuRmHpUctOpRxz1PO5hAB+/OIvpqWGV2YmK
BrfVCz/53PltxxAPDwbI3YPOWthZrtt7bBf8N8kHRLcAbtYqCYC7AY1KyWjsfi7U
V6YQTVZ5YQkBUpJUs/bgf0IOfNh8iKwm/fI8jrvQeYQ/cdABsU7J2wNhDCfQmnRy
Qsz3oBqBAUfQbebAgWhpmY4PoRdSjzLIUdwUDxFJz6xCk78yj6vi9DSoLPn/eAmS
DpJcpucM11g=
-----END AGE ENCRYPTED FILE-----'''
