nushell_completions = [
  "ack",
  "as",
  "bat",
  "btm",
  "cargo",
  "cargo-make",
  "curl",
  "docker",
  "eza",
  "gh",
  "git",
  "just",
  "less",
  "make",
  "man",
  "npm",
  "pre-commit",
  "pytest",
  "rg",
  "rustup",
  "scoop",
  "ssh",
  "tar",
  "typst",
  "uv",
  "vscode",
  "zoxide",
]
